{% set name = "fastTSNE" %}
{% set version = "0.2.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dfe0daef0355d7e32c7f6af32bafe36ac2e9116b793aacfb004da7774c9dd795

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - numba >=0.38.1
    - python
    - scikit-learn >=0.19,<0.19.99
    - scipy

test:
  imports:
    - fastTSNE

about:
  home: https://github.com/pavlin-policar/fastTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast, parallel implementations of tSNE
  dev_url: https://github.com/pavlin-policar/fastTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
