{% set name = "fastTSNE" %}
{% set version = "0.2.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8aa0156178982b833d09a4838d00c16ed933146a433515d54c1fa03f78a6af1

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - numba >=0.38.1
    - python
    - scikit-learn >=0.20
    - scipy

test:
  imports:
    - fastTSNE

about:
  home: https://github.com/pavlin-policar/fastTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast, parallel implementations of tSNE
  dev_url: https://github.com/pavlin-policar/fastTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
